title: Orrich.io Apps
description: orrich.io apps and more.
url: htt://orrich.io/Materialize-Jekyll/
keywords: ["Programming", "Blog"]
timezone: US/EST
permalink: pretty

about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porta, odio vitae sodales malesuada, nibh diam convallis lectus, non scelerisque arcu lectus non nisi. Etiam tincidunt libero eget urna tristique faucibus. Pellentesque varius mi at placerat lobortis. Donec nec aliquam augue. Cras in gravida urna. Nulla dignissim semper accumsan. Nullam mattis felis metus, nec accumsan lorem porta et. Ut dictum dapibus est. In eu ultricies lorem. Duis semper elementum arcu, in rutrum tellus ornare eu."

author:
  codepen: 
  disqus: 
  dribbble: 
  email: 
  facebook: 
  flickr: 
  foursquare: 
  github: orrichio # required
  google_analytics: 
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: Steve # required
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram: 
  tumblr: 
  twitter: 
  weibo: 
  xing: 
  youtube: 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: "/blog/page/:num/"

sass:
  style: compressed
